### ISSUE TITLE
how can i use  the .obj file to measure?

### ISSUE THREAD

**Issue by MuhammadAshiqAmeer** [DavidBoja/SMPL-Anthropometry#12]
Hello David,
i generated a .objl file from an image using smplx model, i want to measure and get measurements from the generated .obj file. Unfortunately i cant see where should i place the .obj file.

**Comment by DavidBoja** [comment]
Hi,

if you have an .obj of an SMPLX model you can follow the `measure.py` main part and adapt it to your needs. Something like this:

```python
import trimesh
from measure import MeasureBody
from pprint import pprint

mesh = trimesh.load("path-to-your-smplx-file.obj")
vertices = mesh.vertices

measurer = MeasureBody("smplx")
measurer.from_verts(verts=vertices)

measurement_names = measurer.all_possible_measurements
measurer.measure(measurement_names)
print("Measurements")
pprint(measurer.measurements)
```

Check [this](https://github.com/mikedh/trimesh/issues/507#issuecomment-515491388) if you have problem loading the .obj mesh with trimesh.

**Comment by MuhammadAshiqAmeer** [comment]
Thanks for the reply. I figured it out some day before. Great work btw
