### ISSUE TITLE
converts a 2D image into a 3D image

### ISSUE THREAD

**Issue by osamaaldnoh** [DavidBoja/SMPL-Anthropometry#16]
Brother, please can you direct me to a model that converts a 2D image into a 3D image so that I can use your project

**Comment by DavidBoja** [comment]
You have some great papers mentioned in the other open issue [here](https://github.com/DavidBoja/SMPL-Anthropometry/issues/15#issuecomment-1912119197). These estimate an SMPL body model given a 2D image of a person.
