### ISSUE TITLE
Where are the model weights (pkl) for SMPL and SMPLx ?

### ISSUE THREAD

**Issue by arunpandian7** [DavidBoja/SMPL-Anthropometry#19]
Thank you for your contribution. But unfortunately there is no topic in README.md that discusses about where to download the model weights for running the demo.

**Comment by DavidBoja** [comment]
I updated the readme.

you can find all the models [here](https://github.com/vchoutas/smplx#downloading-the-model) -- you will need to sign up to be able to download the models. I am using the original SMPL body model.
