### ISSUE TITLE
customization project offer

### ISSUE THREAD

**Issue by wensherix** [DavidBoja/SMPL-Anthropometry#20]
Hi David  i'm interested in more customization of this project for a mobile app are you available???

**Comment by wensherix** [comment]
get in touch on wensherix@live.com

**Comment by DavidBoja** [comment]
Hi,

for any inquiries you can reach me on LinkedIn www.linkedin.com/in/dbojanic
Thanks.

**Comment by wensherix** [comment]
Hi;
Thank you for our reply
Do you have skype or are you ok with zoom meeting?

regards

Addar
________________________________
