### ISSUE TITLE
Custom meshes as input

### ISSUE THREAD

**Issue by YeeZ93** [DavidBoja/SMPL-Anthropometry#25]
Thanks so much for the work!

I am wondering if randomly posed SMPL-X data is acceptable as inputs? Will it lead to significant measurement errors?
For instance:

![20241031222634](https://github.com/user-attachments/assets/587176a8-1bd9-4a5d-9f86-9dbd1e5bd932)

![FB5C3584-C9EE-4160-A7B7-AF4ECED167B0](https://github.com/user-attachments/assets/a2f2b517-ac06-4937-9f0d-62f303a2d348)

![20241031224432](https://github.com/user-attachments/assets/29d2c5fd-6fd1-4c02-ac82-13326a27aa37)

Thanks in advance.

**Comment by Jun-Pu** [comment]
To supplement,
 
Is there a method by which I can get the T-pose meshes corresponding to my inputs?

Much appreciate！

**Comment by YeeZ93** [comment]
To supplement,

Is there a method by which I can get the T-pose meshes corresponding to my inputs?

Much appreciated!

**Comment by YeeZ93** [comment]
Thx, the https://shapy.is.tue.mpg.de/ seems solve the problem
