### ISSUE TITLE
Can we put actual person Height to calculate with the other body parts ?

### ISSUE THREAD

**Issue by TharHtetAungg** [DavidBoja/SMPL-Anthropometry#3]
Can we add a person's actual height to calculate the other body parts? Right now, my 3D body height is not correct, so I want to use my own actual height and calculate the other body parts.

**Comment by DavidBoja** [comment]
You mean correct the measurements you get from the model by scaling them using your actual height?
Yes, from the README:

https://github.com/DavidBoja/SMPL-Anthropometry/blob/c39a5161fd5a411c033cb42c3805b64098e81fbc/README.md?plain=1#L159-L165

you can use `height_normalize_measurements` to scale all measurements using a specified height.  The code snippet measures the SMPL body model (given its shape and gender) and then scales the mesaurements as so:

```
new_measurement = (old_measurement / old_height) * new_height
```

You can get the new normalized measurements using `measurer.height_normalized_measurements`

**Comment by TharHtetAungg** [comment]
Thank you for your reply. I figure it out and I got the result. Thanks @DavidBoja .
