### ISSUE TITLE
please share link for SMPL_NEUTRAL.pkl

### ISSUE THREAD

**Issue by kuldeepbishnoi** [DavidBoja/SMPL-Anthropometry#5]

**Comment by DavidBoja** [comment]
Hello,

you can find all the links [here](https://github.com/vchoutas/smplx#downloading-the-model) -- fyi you will need to sign up to be able to download the models. I am using the original SMPL body model.

**Comment by DavidBoja** [comment]
Closing this issue -- feel free to re-open if you still can't find the body models.
