### ISSUE TITLE
How to measure specific body parts?

### ISSUE THREAD

**Issue by MilesTheProwler** [DavidBoja/SMPL-Anthropometry#6]
Hello, how can I measure specific body parts like under bust for women? I know I can edit the code in the measurement definition but I don't have landmark indices for under bust part, how do you get landmarks indices? 
Thanks.

**Comment by DavidBoja** [comment]
The landmark indices are not exact unfortunately. 
I defined the landmarks using indices from the SMPL body model by manually selecting points I believe should correspond to landmarks + combining with the landmarks from the [SHAPY](https://github.com/muelea/shapy) implementation (you can take a look under <ins>shapy/mesh-mesh-intersection/data</ins>).

A possible solution could be to use the CAESAR or similar datasets (which should contain scans, landmarks and SMPL bodies fitted to the scans) to determine where the landmarks should be on the SMPL body model by looking at where the ground truth landmarks are. Unfortunately I do not possess such a dataset. 
The issue with this however, is the question of how exactly were the SMPL bodies fitted to the scans -- the process usually uses landmarks to do so. Nevertheless, the process usually uses more "important" landmarks, and not under-bust landmarks (for example), which means you should be able to infer those from the fitting.
Hope this makes sense.

**Comment by MilesTheProwler** [comment]
Thanks
