### ISSUE TITLE
Enable to use SMPLX model

### ISSUE THREAD

**Issue by dn0418** [DavidBoja/SMPL-Anthropometry#8]
Hello DavidBoja, It's me, Daniel, I hope your everything is going well.
I am an AI & Machine Learning developer. I am so interested in your excellent projects. 🥇 
I have been studying about 3D human body measurement.
I'd like to help you update your project that SMPLX model can be measured. or have you already revised this project?
If not so, please tell me about detail steps. I will update.
I have already read carefully your suggestion.

(is it ok to use smpl_body_parts_2_faces.json again in measuring SMPLX model?)

By the way, I'd also like to get along with you as a friend.
Could you possibly let me know your any contact info( skype, telegram, discord or email etc)? I will contact through that for more conventional discussion about AI projects.
I will be looking forward to back hearing from you soon.  :)
Thanks.

**Comment by DavidBoja** [comment]
Hi Daniel, sorry for the late reply, I've been occupied with other projects.

I have started working on an update for SMPLX that should soon be ready. 
No, `smpl_body_parts_2_faces.json` will not work for SMPLX since the number of faces is different than SMPL.

Sure thing, I'm always up for a chat - you can add me on [LinkedIn](https://www.linkedin.com/in/dbojanic).

**Comment by dn0418** [comment]
Hello DavidBoja, Thank you for your reply and sorry to bother your busy
time, I hope everything you do is going well.
I will follow you anytime

**Comment by DavidBoja** [comment]
Hi Daniel,

just pushed the latest code - I refactored things a bit and added the possibility to measure the SMPLX body model. 
Let me know if there are any issues :).

**Comment by dn0418** [comment]
Hi David, I hope you are well. Thank you for your great efforts. I have
tested your project and this works well for SMPLX.
I thank you again for your excellent project.
As an AI & Machine Learning Engineer, I'd like to work with you and help
with your work.
How about?

**Comment by DavidBoja** [comment]
Thats great.
Sure, you can reach out on [LinkedIn](https://www.linkedin.com/in/dbojanic) :).

**Comment by dn0418** [comment]
Hello DavidBoja, I hope your everything is going well.
Could you let me know your Skype id? I will contact you for more
comfortable discussion.
My Skype id is live:.cid.595c6592afd7757e
thanks

**Comment by dn0418** [comment]
Hello David, are you having a good time.
Have you read my message?
