### ISSUE TITLE
How to measure length between the two mouse cursor?

### ISSUE THREAD

**Issue by Deep0821** [DavidBoja/SMPL-Anthropometry#9]
Thanks for your great work. I need to implement functionality to measure between the two points when I click the two point using mouse. Could you possibly let me know how to do it? Thanks.

**Comment by DavidBoja** [comment]
Hi, sorry for the late reply!

To measure the distance between two arbitrary points A and B on the body, you could do:

1. something like [this](https://trimsh.org/examples/shortest.html) where they follow the shortest path along the edges between two vertices of the mesh:
    - Find the closest mesh vertices on the body to A and B
    - find their distance between these vertices using the code
    - add the distance from the mesh vertices and the points A and B
2. something similar to the `measure_circumference` in `measure.py`:
    - define a plane with three points: points A and B, and a third random point (would be better if this third point was on the "opposite" side of the body than the first two)
    - use the `trimesh.intersections.mesh_plane` to find the slice segments between the plane and mesh
    - use the segments to find your distance
    - you could first find the closest point in the segments to point A
    - then start from this point and iteratively find the next closest segment, forming a loop measurement until you reach the closest segment to point B
    - Note1: you need to define a method to know if you're measuring from A to B or from B to A
    - Note2: points A and B might be on a segment, so if you need a precise measurements, take that into consideration
    - Note3: if you slice the body with a plane, you can get multiple slices - you should know the region of your measurement so you can eliminate the unnecessary slices

**Comment by DavidBoja** [comment]
Closing issue -- feel free to re-open if you will have further questions.
